version: '3.8'
services:
  arma3:
    build: .
    image: synixebrett/arma3server
    platform: linux/amd64
    container_name: arma3
    network_mode: host
    volumes:
      - arma3root:/arma3
      - steamcmd:/steamcmd
      - './missions:/arma3/mpmissions'
      - './configs:/arma3/configs'
      - './mods:/arma3/mods'
      - './servermods:/arma3/servermods'
    env_file: .env
    restart: unless-stopped
volumes:
  arma3root:
  steamcmd:

